### ISSUE TITLE
Runtime error:dimension specified as 0 but tensor has no dimensions

### ISSUE THREAD

**Issue by nishant9272** [satyenrajpal/Concrete-Crack-Detection#32]
nishant@nishant-HP-15-Notebook-PC:~/Desktop/CrackCrawler$ python3.6 main.py --mode train
Preprocessed dataset...
Dataset statistics: 
 Training examples: 672 positive (crack) & 833 negative (background).
Validation examples: 287 positive (crack) & 356 negative (background).
Running epoch - 0
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    solver.train()
  File "/home/nishant/Desktop/CrackCrawler/solver.py", line 114, in train
    loss = ce_loss(logits, labels.squeeze().long())
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py", line 759, in forward
    self.ignore_index, self.reduce)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1442, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, size_average, ignore_index, reduce)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1328, in nll_loss
    if input.size(0) != target.size(0):
RuntimeError: dimension specified as 0 but tensor has no dimensions

please help as i am stucked here

**Comment by Magiczhuu** [comment]
Do you  solve it?
